---
name: "test-workflow"
on:
  pull_request:
    types: [closed]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deployment
    if: github.event.pull_request.merged
    steps:
    - name: Tag
      uses: K-Phoen/semver-release-action@master
      with:
        release_branch: main
        release_strategy: tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    