---
name: "test-workflow"
on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: "Semver action"
      id: semver-tag
      uses: gandarez/semver-action@v1.0.1
      with:
        prefix: ""
        prerelease_id: "alpha"
        main_branch_name: "main"
        develop_branch_name: ${{ github.ref_name }}
        debug: "true"
    - name: "Created tag"
      run: echo "tag ${{ steps.semver-tag.outputs.semver_tag }}"