---
name: "test-workflow"
on:
  pull_request:
    types:
      - closed
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deployment
    if: github.event.pull_request.merged
    steps:
    - name: Tag
      uses: SOLIDSoftworks/semver-tags@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag-prefix: 'v'
        default-version: '0.1.0'
        create-release: false
        prerelease: 'alpha'
    