---
name: "test-workflow"
on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actionsdesk/semver
      with:
        bump: patch
        prerelease: withBuildNumber
        prelabel: beta
        initial_version: '0.1.1'