---
name: "test-workflow"
on:
  pull_request:
    types:
      - closed
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deployment
    if: github.event.pull_request.merged
    steps:
    - name: Tag
      id: semver_tag
      uses: SOLIDSoftworks/semver-tags@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag-prefix: 'v'
        default-version: '0.1.0'
        create-release: false
        prerelease: ''
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Update setup file
      run: |
        VERSION=${{ steps.semver_tag.outputs.semantic-version }}
        VERSION=$(echo $VERSION | sed s/v//g)
        echo New version: $VERSION
        sed -E s/[0-9]+\.[0-9]+\.[0-9]+/$VERSION/g setup.py | tee setup.py
    - name: Commit setup bump
      uses: devops-infra/action-commit-push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        add_timestamp: true
        commit_prefix: ""
        commit_message: "Bump setup.py version"
        force: false
        target_branch: main

    