---
    name: "test-workflow"
    on:
      pull_request:
        types:
          - closed
    jobs:
      deploy:
        runs-on: ubuntu-latest
        environment: deployment
        # if: github.event.pull_request.merged
        steps:
        - name: Tag
          id: semver_tag
          uses: SOLIDSoftworks/semver-tags@v1
          with:
            GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
            tag-prefix: 'v'
            default-version: '0.1.0'
            create-release: false
            prerelease: ''
            incremented-value: minor
        - name: Checkout Repository
          uses: actions/checkout@v2
          with:
            token: ${{ secrets.REPO_TOKEN }}
        - name: Share Versions
          run: |
            VERSION=${{ steps.semver_tag.outputs.semantic-version }}
            VERSION=$(echo $VERSION | sed s/v//g)
            echo "VERSION=$VERSION" >> $GITHUB_ENV
            PREVIOUS_VERSION=${{ steps.semver_tag.outputs.previous-version }}
            PREVIOUS_VERSION=$(echo $PREVIOUS_VERSION | sed s/v//g)
            echo "PREVIOUS_VERSION=$PREVIOUS_VERSION" >> $GITHUB_ENV
            echo $PREVIOUS_VERSION --> $VERSION
    
        - uses: datamonsters/replace-action@v2
          with:
            files: setup.py
            replacements: '${{ env.PREVIOUS_VERSION }}=${{ env.VERSION }}'

        - name: Remove Extra File
          run: |
            if [[ -f ${{ env.VERSION }} ]]; then
              rm -f ${{ env.VERSION }}
              echo "Deleted version file created by datamonsters/replace-action"
            fi
    
        - name: Commit setup bump
          uses: devops-infra/action-commit-push@master
          with:
            github_token: ${{ secrets.REPO_TOKEN }}
            commit_message: "Bump setup.py to ${{ steps.semver_tag.outputs.semantic-version }}"
            force: true
        