---
name: Update Version
on:
  pull_request:
    types:
      - closed
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deployment
    if: github.event.pull_request.merged
    steps:
    - name: Tag
      id: semver_tag
      uses: SOLIDSoftworks/semver-tags@v1
      with:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        tag-prefix: 'v'
        default-version: '0.1.0'
        create-release: false
        prerelease: ''
        incremented-value: patch
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.REPO_TOKEN }}
    - name: Share Versions
      run: |
        VERSION=${{ steps.semver_tag.outputs.semantic-version }}
        VERSION=$(echo $VERSION | sed s/v//g)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        PREVIOUS_VERSION=${{ steps.semver_tag.outputs.previous-version }}
        PREVIOUS_VERSION=$(echo $PREVIOUS_VERSION | sed s/v//g)
        echo "PREVIOUS_VERSION=$PREVIOUS_VERSION" >> $GITHUB_ENV
        PROJECT_REP="version = \"$PREVIOUS_VERSION\""
        echo "PROJECT_REP=$PROJECT_REP" >> $GITHUB_ENV
        PROJECT_REP_DEST="version = \"$VERSION\""
        echo "PROJECT_REP_DEST=$PROJECT_REP_DEST" >> $GITHUB_ENV
        echo $PREVIOUS_VERSION --> $VERSION
    - name: Update Files
      uses: datamonsters/replace-action@v2
      with:
        files: setup.py
        replacements: '${{ env.PREVIOUS_VERSION }}=${{ env.VERSION }}'

    - name: Update Project File
      uses: datamonsters/replace-action@v2
      with:
        files: pyproject.toml
        replacements: ${{ env.PROJECT_REP }}=${{ env.PROJECT_REP_DEST }}

    - name: Remove Extra File
      run: |
        if [[ -f ${{ env.VERSION }} ]]; then
          rm -f ${{ env.VERSION }}
          echo "Deleted version file created by datamonsters/replace-action"
        fi
    - name: Commit setup bump
      uses: devops-infra/action-commit-push@master
      with:
        github_token: ${{ secrets.REPO_TOKEN }}
        commit_message: "Bump setup.py to ${{ steps.semver_tag.outputs.semantic-version }}"
        force: true
    